ALTER TABLE COTIZACNS.RFD_REFERIDOS ADD AFP VARCHAR2(500) NULL;
ALTER TABLE COTIZACNS.RFD_REFERIDOS ADD PRIMA VARCHAR2(500) NULL;
ALTER TABLE COTIZACNS.RFD_REFERENCIAS ADD PRIORITARIO NUMBER(1,0) NULL;
